### ISSUE TITLE
Version Error message - v 2.3.0.2

### ISSUE THREAD

**Issue by sonnylaskar** [sherzberg/graylog-plugin-s3#9]
Hi,

The below error pops up with version 2.3.0.2

> 2017-11-25T05:58:15.730Z ERROR [Version] Unable to read org.sherzberg.graylog.plugins.graylog-plugin-s3/graylog-plugin.properties, this build has no version number.
> com.github.zafarkhaja.semver.UnexpectedCharacterException: null
>         at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516) ~[graylog.jar:?]
>         at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:259) ~[graylog.jar:?]
>         at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195) ~[graylog.jar:?]
>         at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265) ~[graylog.jar:?]
>         at org.graylog2.plugin.Version.fromClasspathProperties(Version.java:219) [graylog.jar:?]
>         at org.graylog2.plugin.Version.fromPluginProperties(Version.java:163) [graylog.jar:?]
>         at org.sherzberg.graylog.aws.plugin.S3InputPluginMetaData.getVersion(S3InputPluginMetaData.java:39) [graylog-plugin-s3-2.3.0.2-SNAPSHOT.jar:?]
>         at org.graylog2.shared.plugins.PluginLoader$PluginAdapter.toString(PluginLoader.java:193) [graylog.jar:?]
>         at org.apache.logging.log4j.message.ParameterFormatter.tryObjectToString(ParameterFormatter.java:614) [graylog.jar:?]
>         at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:434) [graylog.jar:?]
>         at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:189) [graylog.jar:?]
>         at org.apache.logging.log4j.message.ReusableParameterizedMessage.formatTo(ReusableParameterizedMessage.java:313) [graylog.jar:?]
>         at org.apache.logging.log4j.core.impl.MutableLogEvent.setMessage(MutableLogEvent.java:214) [graylog.jar:?]
>         at org.apache.logging.log4j.core.impl.ReusableLogEventFactory.createEvent(ReusableLogEventFactory.java:81) [graylog.jar:?]
>         at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:401) [graylog.jar:?]
>         at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) [graylog.jar:?]
>         at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) [graylog.jar:?]
>         at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) [graylog.jar:?]
>         at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005) [graylog.jar:?]
>         at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1876) [graylog.jar:?]
>         at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184) [graylog.jar:?]
>         at org.graylog2.bootstrap.CmdLineTool.loadPlugins(CmdLineTool.java:298) [graylog.jar:?]
>         at org.graylog2.bootstrap.CmdLineTool.installPluginConfigAndBindings(CmdLineTool.java:269) [graylog.jar:?]
>         at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:171) [graylog.jar:?]
>         at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
>

**Comment by bjmgeek** [comment]
I see the same error with Graylog 2.5.1+34194da

[server.log](https://github.com/sherzberg/graylog-plugin-s3/files/2818837/server.log)

**Comment by stevecalvert** [comment]
Had the same 'build has no version number' error with v2.3.0.2 and Graylog 2.4.3 :( 
Would really like to aggregate S3 logs into Graylog, and this plugin looked ideal, but appears to no longer be supported.  Has anyone come across a fix, workaround or alternate solution?

**Comment by baumstern** [comment]
I see the same error with `graylog/graylog:3.0` image
